---
apiVersion: v2
name: reloader
description: Deploy K8s Reloader

type: application

# This is the chart version, but is ignored by ArgoCD
version: 0.1.0

dependencies:
  - name: cert-manager
    version: v1.15.1
    repository: https://charts.jetstack.io
